version: '3'

vars:
  TRACKED_FILES_NL:
    sh: git ls-files "*.py"
  TRACKED_FILES: "{{.TRACKED_FILES_NL | catLines}}"

tasks:
  fmt:
    cmds:
    - python -m isort --profile black {{.TRACKED_FILES}}
    - python -m black {{.TRACKED_FILES}}

  format: 
    cmds:
    - task: fmt

  lint-only:
    cmds:
    - python -m pylint {{.TRACKED_FILES}}

  lint:
    cmds:
    - task: fmt
    - task: lint-only

  check-format:
    cmds:
    - python -m isort --profile black --check {{.TRACKED_FILES}}
    - python -m black --check {{.TRACKED_FILES}}
